remote_theme: ISSAE/architect

name: Java Web EE / au Cnam Liban

author: Pascal Fares

author_email: pascal.fares@isae.edu.lb

title: Java Web EE 

google_analytics: UA-29708002-2

repository: ISSAE/java-ee

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

